/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../App`; params?: Router.UnknownInputParams; } | { pathname: `/../components/Header`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ItemsPreview`; params?: Router.UnknownInputParams; } | { pathname: `/../components/FilterChips`; params?: Router.UnknownInputParams; } | { pathname: `/../components/OutfitCollections`; params?: Router.UnknownInputParams; } | { pathname: `/../types/index`; params?: Router.UnknownInputParams; } | { pathname: `/../data/mockData`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../App`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/Header`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ItemsPreview`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/FilterChips`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/OutfitCollections`; params?: Router.UnknownOutputParams; } | { pathname: `/../types/index`; params?: Router.UnknownOutputParams; } | { pathname: `/../data/mockData`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/../App${`?${string}` | `#${string}` | ''}` | `/../components/Header${`?${string}` | `#${string}` | ''}` | `/../components/ItemsPreview${`?${string}` | `#${string}` | ''}` | `/../components/FilterChips${`?${string}` | `#${string}` | ''}` | `/../components/OutfitCollections${`?${string}` | `#${string}` | ''}` | `/../types/index${`?${string}` | `#${string}` | ''}` | `/../data/mockData${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../App`; params?: Router.UnknownInputParams; } | { pathname: `/../components/Header`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ItemsPreview`; params?: Router.UnknownInputParams; } | { pathname: `/../components/FilterChips`; params?: Router.UnknownInputParams; } | { pathname: `/../components/OutfitCollections`; params?: Router.UnknownInputParams; } | { pathname: `/../types/index`; params?: Router.UnknownInputParams; } | { pathname: `/../data/mockData`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
